#### general settings
name: esrgan_can2_train_lr2mr
use_tb_logger: true
model: srgan
distortion: sr
scale: 2
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: can2_train_lr2mr
    mode: LQGT
    dataroot_GT: /workspace/sst_datasets/MR/can2/train
    dataroot_LQ: /workspace/sst_datasets/LR/can2/train

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 32
    GT_size: 32
    use_flip: false
    use_rot: false
    color: gray
  val:
    name: can2_valid_lr2mr
    mode: LQGT
    dataroot_GT: /workspace/sst_datasets/MR/can2/valid
    dataroot_LQ: /workspace/sst_datasets/LR/can2/valid

#### network structures
network_G:
  which_model_G: RRDBNet
  in_nc: 1
  out_nc: 1
  nf: 64
  nb: 23
network_D:
  which_model_D: discriminator_vgg_128
  in_nc: 1
  nf: 64

#### path
path:
  pretrain_model_G: /workspace/experiments/rrdbnet_can2_train_lr2mr/models/latest_G.pth
  strict_load: true
  resume_state: /workspace/experiments/esrgan_can2_train_lr2mr/training_state/24459.state

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99
  lr_scheme: MultiStepLR

  niter: 25000
  warmup_iter: -1  # no warm up
  lr_steps: [5000, 10000, 15000, 20000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e-2
  feature_criterion: l1
  feature_weight: 1
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 5e-3

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: 263 # !!float 1e4

#### logger
logger:
  print_freq: 263
  save_checkpoint_freq: 263
