#### general settings
name: esrgan_all_train_lr2hr
use_tb_logger: false
model: srgan
distortion: sr
scale: 4
gpu_ids: [1]

#### datasets
datasets:
  train:
    name: all_train_lr2hr
    mode: LQGT
    dataroot_GT: ../sst_datasets/HR/all/train
    dataroot_LQ: ../sst_datasets/LR/all/train

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 32
    GT_size: 64
    use_flip: false
    use_rot: false
    color: gray
  val:
    name: all_valid_lr2hr
    mode: LQGT
    dataroot_GT: ../sst_datasets/HR/all/valid
    dataroot_LQ: ../sst_datasets/LR/all/valid

#### network structures
network_G:
  which_model_G: RRDBNet
  in_nc: 1
  out_nc: 1
  nf: 64
  nb: 23
network_D:
  which_model_D: discriminator_vgg_128
  in_nc: 1
  nf: 64

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99
  lr_scheme: MultiStepLR

  niter: 25000
  warmup_iter: -1  # no warm up
  lr_steps: [5000, 10000, 15000, 20000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e-2
  feature_criterion: l1
  feature_weight: 1
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 5e-3

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: 1578 # !!float 1e4

#### logger
logger:
  print_freq: 1578
  save_checkpoint_freq: 1578
